import { jsPDF } from 'jspdf'
import { toast } from 'react-hot-toast'
import type { Ticket } from '../../features/tickets/types'

const MARGIN_PT = 48
const LINE_PT = 14
const FOOTER_FROM_BOTTOM = 28

function addFooters(doc: jsPDF): void {
  const pageHeight = doc.internal.pageSize.getHeight()
  const pageWidth = doc.internal.pageSize.getWidth()
  const total = doc.getNumberOfPages()
  for (let p = 1; p <= total; p++) {
    doc.setPage(p)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(100, 116, 139)
    doc.text('Generated by BriefAI', MARGIN_PT, pageHeight - FOOTER_FROM_BOTTOM)
    doc.setTextColor(30, 41, 59)
    doc.text(
      `Page ${p} of ${total}`,
      pageWidth - MARGIN_PT,
      pageHeight - FOOTER_FROM_BOTTOM,
      { align: 'right' },
    )
  }
}

/**
 * Build a printable PDF for a set of tickets (shared by Tickets and History flows).
 */
export function generatePDF(tickets: Ticket[], briefTitle: string): void {
  if (tickets.length === 0) {
    toast.error('No tickets to export.')
    return
  }
  try {
    const doc = new jsPDF({ unit: 'pt', format: 'letter' })
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const maxTextWidth = pageWidth - MARGIN_PT * 2
    let y = MARGIN_PT

    const ensureSpace = (extraLines: number) => {
      if (
        y + extraLines * LINE_PT >
        pageHeight - MARGIN_PT - FOOTER_FROM_BOTTOM
      ) {
        doc.addPage()
        y = MARGIN_PT
      }
    }

    const writeWrapped = (text: string, fontSize: number, bold: boolean) => {
      doc.setFont('helvetica', bold ? 'bold' : 'normal')
      doc.setFontSize(fontSize)
      const wrapped = doc.splitTextToSize(text, maxTextWidth)
      for (const line of wrapped) {
        ensureSpace(1)
        doc.text(line, MARGIN_PT, y)
        y += LINE_PT
      }
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(15, 23, 42)
    doc.text('BriefAI — Developer Tickets Report', MARGIN_PT, y)
    y += 22

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(51, 65, 85)
    writeWrapped(`Brief: ${briefTitle || 'Untitled brief'}`, 10, false)
    y += 4
    writeWrapped(
      `Generated: ${new Date().toLocaleString(undefined, {
        dateStyle: 'medium',
        timeStyle: 'short',
      })}`,
      10,
      false,
    )
    y += 12

    doc.setDrawColor(148, 163, 184)
    doc.setLineWidth(0.75)
    doc.line(MARGIN_PT, y, pageWidth - MARGIN_PT, y)
    y += LINE_PT + 4

    tickets.forEach((ticket, index) => {
      if (index > 0) {
        ensureSpace(2)
        doc.setDrawColor(203, 213, 225)
        doc.setLineWidth(0.5)
        doc.line(MARGIN_PT, y + 2, pageWidth - MARGIN_PT, y + 2)
        y += LINE_PT + 6
      }

      const label = `TICKET-${String(index + 1).padStart(3, '0')}`
      writeWrapped(
        `${label}  |  ${ticket.type}  |  ${ticket.priority}`,
        10,
        false,
      )
      y += 4
      writeWrapped(ticket.title, 13, true)
      y += 6
      writeWrapped('Description', 10, true)
      writeWrapped(ticket.description, 10, false)
      y += 4
      writeWrapped('Acceptance criteria', 10, true)
      if (ticket.acceptanceCriteria.length === 0) {
        writeWrapped('— None listed —', 10, false)
      } else {
        ticket.acceptanceCriteria.forEach((c, i) => {
          writeWrapped(`${i + 1}. ${c}`, 10, false)
        })
      }
      y += 8
    })

    addFooters(doc)

    const slug =
      briefTitle
        .replace(/[^\w\s-]/g, '')
        .trim()
        .replace(/\s+/g, '-')
        .slice(0, 48) || 'brief'
    doc.save(`BriefAI-${slug}-${Date.now()}.pdf`)
    toast.success('PDF downloaded successfully!')
  } catch {
    toast.error('Could not generate PDF. Please try again.')
  }
}
